### ISSUE TITLE
react-capstone

### ISSUE THREAD

**Issue by whiteWolfx99** [whiteWolfx99/recipe-capstone#13]
Hi Dear Reviewer!
We created the kanban and the cards. The link to the project is given below:

-Team Member 1: @whiteWolfx99 
-Team Member 2: @vanelnw 
-Team Member 3: @mohamed20163858 

Link to project: https://github.com/users/whiteWolfx99/projects/7/views/1?layout=board

**Comment by omarsalem7** [comment]
Hi @whiteWolfx99, @mohamed20163858 , @vanelnw 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to start on it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ The tasks assigned to each one equally
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
